image: ubuntu:latest

before_script:
  # run shell script for installing arduino-cli, Wio Terminal core, and project libraries
  - chmod +x setup-build-env.sh               # change permissions to execute bash shell script
  - ./setup-build-env.sh                      # execute bash shell script

stages:
  - build
  - test
  - deploy

build application:
  stage: build
  tags:
    - docker
  script:
    - export PATH=$PATH:/root/bin             # set the path to arduino-cli installation folder
    - arduino-cli lib list                    # check that libraries are installed
    - pwd                                     # print the current working directory
    - cd WioTerminal                          # change the directory to arduino folder
    - arduino-cli compile --fqbn Seeeduino:samd:seeed_wio_terminal  # Compile
  #    - arduino-cli board list                  # Upload. Check if device is connected
  except:
    - tags

#test:
#    stage: test
##    tags:
##      - docker
#    script:
#      - echo "All tests are passed."

release:
  stage: deploy
  tags:
    - upload
  script:
    - export PATH=$PATH:/root/bin             # set the path to arduino-cli installation folder
    - pwd                                     # print the current working directory
    - cd WioTerminal                          # change the directory to arduino folder
    - echo "$SECRET_KEY" > Secrets.h
    - arduino-cli lib list                    # check that libraries are installed
    
    - arduino-cli compile --fqbn Seeeduino:samd:seeed_wio_terminal  # Compile
    # Upload
    - arduino-cli board list                  # Check if device is connected
    - arduino-cli upload -p $COM_PORT --fqbn Seeeduino:samd:seeed_wio_terminal           # if runnner is on local machine
  only:
    - tags