image: ubuntu:latest

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"    # disable gradle demon >_< since he fast but may prove inaccurate for CI

before_script:
  # run shell script for installing arduino-cli, Wio Terminal core, and project libraries
  - chmod +x setup-build-env.sh               # change permissions to execute bash shell script
  - ./setup-build-env.sh                      # execute bash shell script
  - GRADLE_USER_HOME="$(pwd)/.gradle"         # set gradle home location as .gradle
  - export GRADLE_USER_HOME                   # export it so its available for gradle


stages:
  - build
  - test
  - deploy

build application:
  stage: build
  image: openjdk:amd64/gradle:8.0.1-jdk19-alpine    # overwrite image 
  # Builds the application
  script: 
    - pwd                                           # for debugging purposes
    - gradle --build-cache assemble  
  artifacts:
    # Saves the built app
    paths:
      - build/distributions/*
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build                                 # whole build directory is cached for test stage
      - .gradle

test:
  stage: test
  image: openjdk:amd64/gradle:8.0.1-jdk19-alpine
  script: gradle check                        # exactly same as gradle test, which runs all the detected unit tests
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

compile:
  stage: build
  tags:
    - docker
  script:
    - export PATH=$PATH:/root/bin             # set the path to arduino-cli installation folder.
    - pwd                                     # print the current working directory
    - cd WioTerminal                          # change the directory to arduino folder
    - echo "$SECRETS_H" > Secrets.h           # import secrets from GitLAB CI/CD Settings -> Variables
    #- echo "$NETWORK_INFO_H" > NetworkInfo.h  # import secrets for WiFi from Gitlab CI/CD Settings -> Variables
    #- echo "$BROKER_INFO_H" > BrokerInfo.h    # import secrets for MQTT from Gitlab CI/CD Settings -> Variables
    - arduino-cli lib list                    # check that libraries are installed
    
    # Compile
    - arduino-cli compile --fqbn Seeeduino:samd:seeed_wio_terminal

    # Upload
    - arduino-cli board list                  # Check if device is connected
  except:
    - tags

release:
  stage: deploy
  tags:
    - upload
  script:
    - export PATH=$PATH:/root/bin             # set the path to arduino-cli installation folder
    - pwd                                     # print the current working directory
    - cd WioTerminal                         # change the directory to arduino folder
    - echo "$SECRETS_H" > Secrets.h           # import secrets from GitLAB CI/CD Settings -> Variables
    #- echo "$NETWORK_INFO_H" > NetworkInfo.h  # import secrets for WiFi from Gitlab CI/CD Settings -> Variables
    #- echo "$BROKER_INFO_H" > BrokerInfo.h    # import secrets for MQTT from Gitlab CI/CD Settings -> Variables
    - arduino-cli lib list                    # check that libraries are installed
    
    # Compile
    - arduino-cli compile --fqbn Seeeduino:samd:seeed_wio_terminal

    # Upload
    - arduino-cli board list                  # Check if device is connected
    - arduino-cli upload -p $COM_PORT --fqbn Seeeduino:samd:seeed_wio_terminal           # if runnner is on local machine
  only:
    - tags