image: ubuntu:latest

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"    # disable gradle demon >_< since he fast but may prove inaccurate for CI

before_script:
  # run shell script for installing arduino-cli, Wio Terminal core, and project libraries
  - cd AquaCare
  - chmod +x setup-build-env.sh               # change permissions to execute bash shell script
  - ./setup-build-env.sh                      # execute bash shell script
  
  #

  #  - chmod +x AquaCare/gradlew                 # elevates permissions
  #  - GRADLE_USER_HOME="$(pwd)/AquaCare/.gradle"         # set gradle home location as .gradle

  - chmod +x gradlew                 # elevates permissions
  - GRADLE_USER_HOME="$(pwd)/AquaCare/.gradle"         # set gradle home location as .gradle
  - export GRADLE_USER_HOME                   # export it so its available for gradle


stages:
  - build
  - test
  - deploy


build application:
  stage: build
  image: amd64/gradle:8.0.1-jdk19-alpine            # overwrite image 
  tags:
    - docker                                        # without explicit tags, docker wont love you
  script:                                           # builds the application 

    # is chaging directories required here?
    #- cd AquaCare                                   # navigate to correct directory
    - ./gradlew --build-cache assemble

  artifacts:                                        # saves the built app               
    paths:
      - AquaCare/build/distributions/AquaCare-1.0-SNAPSHOT/bin/Aquacare.bat
  cache:                                            # caches test related files
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - AquaCare/build                              # whole build directory is cached for test stage
      - AquaCare/.gradle

test:
  stage: test
  image: amd64/gradle:8.0.1-jdk19-alpine    # an image with gradle and java installed just for us to use gradlew
  tags:
    - docker
  script:
    - cd AquaCare                            # gets into correct path
    - ./gradlew check                        # exactly same as gradle test, which runs all the detected unit tests
    - echo "detected unit tests are run"
    - sleep 1

  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull                             # pulls from previously pushed cache
    paths:
      - build
      - .gradle


compile:
  stage: build
  tags:
    - docker
  script:
    - export PATH=$PATH:/root/bin             # set the path to arduino-cli installation folder.
#    - cd ~                                    # go back to the home directory
    - pwd                                     # print the current working directory
#    - cd WioTerminal                          # change the directory to arduino folder
    - echo "$SECRET_KEY" > Secrets.h
    #- echo "$NETWORK_INFO_H" > NetworkInfo.h  # import secrets for WiFi from Gitlab CI/CD Settings -> Variables
    #- echo "$BROKER_INFO_H" > BrokerInfo.h    # import secrets for MQTT from Gitlab CI/CD Settings -> Variables
    - arduino-cli lib list                    # check that libraries are installed
    
    # Compile
    - arduino-cli compile --fqbn Seeeduino:samd:seeed_wio_terminal

    # Upload
    - arduino-cli board list                  # Check if device is connected
  except:
    - tags


release:
  stage: deploy
  tags:
    - upload
  script:
    - export PATH=$PATH:/root/bin             # set the path to arduino-cli installation folder
    - pwd                                     # print the current working directory
    - cd WioTerminal                         # change the directory to arduino folder
    #- echo "$NETWORK_INFO_H" > NetworkInfo.h  # import secrets for WiFi from Gitlab CI/CD Settings -> Variables
    #- echo "$BROKER_INFO_H" > BrokerInfo.h    # import secrets for MQTT from Gitlab CI/CD Settings -> Variables
    - arduino-cli lib list                    # check that libraries are installed
    
    # Compile
    - arduino-cli compile --fqbn Seeeduino:samd:seeed_wio_terminal

    # Upload
    - arduino-cli board list                  # Check if device is connected
    - arduino-cli upload -p $COM_PORT --fqbn Seeeduino:samd:seeed_wio_terminal           # if runnner is on local machine
  only:
    - tags